# Generated by Django 5.0.6 on 2024-06-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstiloTatuaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('old-school', 'Old School'), ('tribal', 'Tribal'), ('irezumi', 'Irezumi'), ('realista', 'Realista'), ('3d', '3D')], max_length=20, unique=True)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='estilos/')),
            ],
        ),
    ]
