# Generated by Django 5.0.6 on 2024-06-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoart', '0002_estilotatuaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tatuaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estilo', models.CharField(choices=[('old-school', 'Old School'), ('tribal', 'Tribal'), ('irezumi', 'Irezumi'), ('realista', 'Realista'), ('3d', '3D')], max_length=20)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='tatuajes/')),
            ],
        ),
        migrations.DeleteModel(
            name='EstiloTatuaje',
        ),
    ]
