# Generated by Django 5.0.6 on 2024-06-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoart', '0003_tatuaje_delete_estilotatuaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
