# Generated by Django 5.0.6 on 2024-06-28 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tattoart', '0004_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='fecha_envio',
        ),
    ]
